GET http://localhost:3000/hello

###

GET http://localhost:3000/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvaSIsInBhc3N3b3JkIjoic2thdGVyIiwibmFtZSI6IkJvaUtld2wiLCJlbWFpbCI6ImJvaUBrZXdsa2lkcy5jb20iLCJpYXQiOjE2ODExMTE1NDYsImV4cCI6MTY4MTExNTE0Nn0.6M9HI5Lnn1MajM0QOxIsk3ic91Eyp5xcCePSD9fWl8Q
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "boi",
    "password": "skater"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "boi",
    "password": "skater",
    "name": "BoiKewl",
    "email": "boi@kewlkids.com"
}
