GET http://localhost:3000/

###

POST http://localhost:3000/bye

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "boi",
    "password": "skater"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "boi",
    "password": "skater",
    "name": "BoiKewl",
    "email": "boi@kewlkids.com"
}
